### PR TITLE
Dev into main; version0.8? 1.0? 

### PR DESCRIPTION
**Pull request by klamkiew**
Alright, we now have IQTree instead of RAxML(-NG), mamba as conda-engine and the ILP files are now linked instead of copied. 
The test set ran on ARA ( -profile conda,slurm) and on my PC ( -profile conda,local ).
@hoelzer  If you could run one or two test with singularity and everything looks neat, I think we can do the PR and use this version as Manuscript-Version ;)

### CODE REVIEW

**Comment by hoelzer** [comment]
Nice one! I will run test(s) and would use the opportunity also to do some clean-up of the README. Replacing the ugly DAG w/ the one we prepared for the paper already maybe, etc... keep you posted here

**Comment by hoelzer** [comment]
test on HPC started:

```bash
 nextflow run hoelzer-lab/ribap -r dev --fasta 'fastas/*.fasta' --tree --bootstrap 100 --output listeria-results --singularityCacheDir /singularity/user/mf1/ribap/ -w work -profile slurm,singularity
```

**Comment by hoelzer** [comment]
Note to myself: bootstrop for IQtree is at least 1000. If a user defines less than 1000 there should be a warning or stop of the wf execution (see other workflows). Can be also noted in the --help

**Comment by hoelzer** [comment]
> test on HPC started:
> 
> ```shell
>  nextflow run hoelzer-lab/ribap -r dev --fasta 'fastas/*.fasta' --tree --bootstrap 100 --output listeria-results --singularityCacheDir /singularity/user/mf1/ribap/ -w work -profile slurm,singularity
> ```

rerun with 1000 bootstraps and worked like a charm @klamkiew on our quite restricted HPC w/ SLURM and Singularity. If it runs there, should run almost everywhere (okay maybe not on ARA ;) ).

**Comment by klamkiew** [comment]
ah yea - the `-bb` parameter of IQTree only likes >=1000 as input. The default is set to this, but you are right, commenting on this in the help is a good idea.

**Comment by hoelzer** [comment]
@klamkiew I updated the README, added the new flow chart picture, and added a check for 1000 minimum bootstrap input and some other meta checks/outputs (warning when output folder exists, etc...).

**Comment by hoelzer** [comment]
ah and I think, when we're happy we can make a `1.0.0` release following https://semver.org/lang/de/ 

But: maybe let's run our example data sets w/ `-r dev` and when they all work and we do not need any more fixes to this branch, we make the merge and release.

**Pull request merged**
